version: "3.8"

services:
  server:
    container_name: django_vpn_server
    build: ./django_vpn_service
    ports:
      - "${SERVER_OUTER_PORT}:8000"
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./django_vpn_service/:/django_vpn_service/